/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PropertyListing {
  'id' : string,
  'status' : PropertyStatus,
  'title' : string,
  'ownerName' : string,
  'propertyType' : PropertyType,
  'ownerId' : Principal,
  'area' : string,
  'city' : string,
  'createdAt' : bigint,
  'description' : string,
  'amenities' : Array<string>,
  'viewCount' : bigint,
  'isFeatured' : boolean,
  'address' : string,
  'rentPerMonth' : bigint,
  'contactPhone' : string,
  'images' : Array<ExternalBlob>,
}
export interface PropertyListingInput {
  'title' : string,
  'ownerName' : string,
  'propertyType' : PropertyType,
  'area' : string,
  'city' : string,
  'description' : string,
  'amenities' : Array<string>,
  'address' : string,
  'rentPerMonth' : bigint,
  'contactPhone' : string,
  'images' : Array<ExternalBlob>,
}
export type PropertyStatus = { 'rented' : null } |
  { 'available' : null };
export type PropertyType = { 'pg' : null } |
  { 'studio' : null } |
  { 'bhk1' : null } |
  { 'bhk2' : null } |
  { 'bachelorRoom' : null } |
  { 'hostel' : null };
export interface SearchFilters {
  'propertyType' : [] | [PropertyType],
  'minRent' : [] | [bigint],
  'city' : [] | [string],
  'keyword' : [] | [string],
  'maxRent' : [] | [bigint],
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToFavorites' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPropertyListing' : ActorMethod<[PropertyListingInput], string>,
  'deletePropertyListing' : ActorMethod<[string], undefined>,
  'getAllListings' : ActorMethod<[], Array<PropertyListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[string], PropertyListing>,
  'getListingCountByCity' : ActorMethod<[], Array<[string, bigint]>>,
  'getListingsByOwner' : ActorMethod<[Principal], Array<PropertyListing>>,
  'getMostViewedListings' : ActorMethod<[bigint], Array<PropertyListing>>,
  'getPropertyListing' : ActorMethod<[string], PropertyListing>,
  'getPropertyTypes' : ActorMethod<[], Array<string>>,
  'getUserFavorites' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markListingAvailable' : ActorMethod<[string], undefined>,
  'markListingRented' : ActorMethod<[string], undefined>,
  'removeFromFavorites' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPropertyListings' : ActorMethod<
    [SearchFilters],
    Array<PropertyListing>
  >,
  'updatePropertyListing' : ActorMethod<
    [string, PropertyListingInput],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];