/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'pg' : IDL.Null,
  'studio' : IDL.Null,
  'bhk1' : IDL.Null,
  'bhk2' : IDL.Null,
  'bachelorRoom' : IDL.Null,
  'hostel' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PropertyListingInput = IDL.Record({
  'title' : IDL.Text,
  'ownerName' : IDL.Text,
  'propertyType' : PropertyType,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'rentPerMonth' : IDL.Nat,
  'contactPhone' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const PropertyStatus = IDL.Variant({
  'rented' : IDL.Null,
  'available' : IDL.Null,
});
export const PropertyListing = IDL.Record({
  'id' : IDL.Text,
  'status' : PropertyStatus,
  'title' : IDL.Text,
  'ownerName' : IDL.Text,
  'propertyType' : PropertyType,
  'ownerId' : IDL.Principal,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'viewCount' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'address' : IDL.Text,
  'rentPerMonth' : IDL.Nat,
  'contactPhone' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const SearchFilters = IDL.Record({
  'propertyType' : IDL.Opt(PropertyType),
  'minRent' : IDL.Opt(IDL.Nat),
  'city' : IDL.Opt(IDL.Text),
  'keyword' : IDL.Opt(IDL.Text),
  'maxRent' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToFavorites' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPropertyListing' : IDL.Func([PropertyListingInput], [IDL.Text], []),
  'deletePropertyListing' : IDL.Func([IDL.Text], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Text], [PropertyListing], ['query']),
  'getListingCountByCity' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getListingsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getMostViewedListings' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getPropertyListing' : IDL.Func([IDL.Text], [PropertyListing], []),
  'getPropertyTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markListingAvailable' : IDL.Func([IDL.Text], [], []),
  'markListingRented' : IDL.Func([IDL.Text], [], []),
  'removeFromFavorites' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPropertyListings' : IDL.Func(
      [SearchFilters],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'updatePropertyListing' : IDL.Func([IDL.Text, PropertyListingInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'pg' : IDL.Null,
    'studio' : IDL.Null,
    'bhk1' : IDL.Null,
    'bhk2' : IDL.Null,
    'bachelorRoom' : IDL.Null,
    'hostel' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PropertyListingInput = IDL.Record({
    'title' : IDL.Text,
    'ownerName' : IDL.Text,
    'propertyType' : PropertyType,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'rentPerMonth' : IDL.Nat,
    'contactPhone' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const PropertyStatus = IDL.Variant({
    'rented' : IDL.Null,
    'available' : IDL.Null,
  });
  const PropertyListing = IDL.Record({
    'id' : IDL.Text,
    'status' : PropertyStatus,
    'title' : IDL.Text,
    'ownerName' : IDL.Text,
    'propertyType' : PropertyType,
    'ownerId' : IDL.Principal,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'viewCount' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'address' : IDL.Text,
    'rentPerMonth' : IDL.Nat,
    'contactPhone' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const SearchFilters = IDL.Record({
    'propertyType' : IDL.Opt(PropertyType),
    'minRent' : IDL.Opt(IDL.Nat),
    'city' : IDL.Opt(IDL.Text),
    'keyword' : IDL.Opt(IDL.Text),
    'maxRent' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToFavorites' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPropertyListing' : IDL.Func([PropertyListingInput], [IDL.Text], []),
    'deletePropertyListing' : IDL.Func([IDL.Text], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Text], [PropertyListing], ['query']),
    'getListingCountByCity' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getListingsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getMostViewedListings' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getPropertyListing' : IDL.Func([IDL.Text], [PropertyListing], []),
    'getPropertyTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markListingAvailable' : IDL.Func([IDL.Text], [], []),
    'markListingRented' : IDL.Func([IDL.Text], [], []),
    'removeFromFavorites' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPropertyListings' : IDL.Func(
        [SearchFilters],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'updatePropertyListing' : IDL.Func(
        [IDL.Text, PropertyListingInput],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };